#!/bin/bash

# remove everything we're about to build
find docs/* ! \( -iname "conf.py" -or -iname "makePackageRSTs.py" -or -path "*_static/*" -or -path "*_templates/*" -or -path "*narrative/*" -or -path "*index.rst" \) -delete

cd docs
python3 ./makePackageRSTs.py

sphinx-build . build

firefox build/index.html
