#!/bin/bash
EXCLUSIONS=scamp/thirdparty\ scamp/dependencies.py

# remove everything except the conf file
find docs/* ! \( -iname "conf.py" -or -path "*_static/*" -or -path "*index.rst" \) -delete
# generate the api documentation, excluding the defined directories
sphinx-apidoc -F -o docs scamp $EXCLUSIONS
cd docs
make html
firefox _build/html/index.html
