#!/bin/bash
# NOTE: THIS SOURCE FILE WAS GENERATED BY CLAUDE OPUS 4.8 WITH LITTLE HUMAN OVERSIGHT
# PLEASE REVIEW THE AI POLICY AT REPOSITORY ROOT FOR MORE INFORMATION
# Build the Sphinx docs into scamp/docs_build. Regenerates the API .rst files
# every time; the example pages change less often, so they are rebuilt only with
# --rebuild-examples (or automatically when missing, e.g. on a fresh checkout).
set -euo pipefail

REBUILD_EXAMPLES=0
for arg in "$@"; do
    case "$arg" in
        --rebuild-examples|--rebuild_examples) REBUILD_EXAMPLES=1 ;;
        *) echo "unknown argument: $arg" >&2; exit 1 ;;
    esac
done

# Run from the package root regardless of where we were invoked from.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Remove the generated API rst we're about to rebuild. Hand-written sources, the
# examples/ tree, and the build_text tutor bundle are preserved. (find reports the
# kept, non-empty directories as "not empty" -- harmless, hence || true.)
find docs/* ! \( -iname "conf.py" -or -iname "makePackageRSTs.py" \
    -or -iname "build_examples_docs.py" -or -iname "example_media.toml" \
    -or -iname "README.md" \
    -or -path "*_static/*" -or -path "*_templates/*" -or -path "*narrative/*" \
    -or -path "*examples/*" -or -path "*build_text/*" -or -path "*index.rst" \) -delete || true

cd docs
python3 ./makePackageRSTs.py
# The example pages change rarely, so regenerate them only on request -- or
# automatically when absent (e.g. a fresh checkout), since they aren't tracked.
if [ "$REBUILD_EXAMPLES" = "1" ] || [ ! -d examples ]; then
    python3 ./build_examples_docs.py
fi

sphinx-build . ../docs_build

firefox ../docs_build/index.html
